CREATE DATABASE RIKKEICLINICDB;
USE RIKKEICLINICDB;

-- 1. BẢNG BỆNH NHÂN (PATIENTS)
CREATE TABLE PATIENTS (
    PATIENT_ID INT PRIMARY KEY,
    FULL_NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(15) UNIQUE NOT NULL,
    DATE_OF_BIRTH DATE
);

-- 9. BẢNG SẢN PHẨM (PRODUCTS)
CREATE TABLE PRODUCTS (
    PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL,
    PRICE DECIMAL(18,2) NOT NULL,
    STOCK INT NOT NULL DEFAULT 0
);

-- 11. BẢNG VÍ ĐIỆN TỬ (WALLETS) 
CREATE TABLE WALLETS (
    PATIENT_ID INT PRIMARY KEY,
    BALANCE DECIMAL(18,2) NOT NULL DEFAULT 0,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID)
);

-- CHÈN BỆNH NHÂN
INSERT INTO PATIENTS (PATIENT_ID, FULL_NAME, PHONE, DATE_OF_BIRTH) VALUES
(1, 'NGUYEN VAN AN', '0901111222', '1990-05-15'),
(2, 'TRAN THI BINH', '0912222333', '1985-08-20'),
(3, 'LE HOANG CUONG', '0923333444', '2000-12-01');

-- CHÈN SẢN PHẨM E-COMMERCE 
INSERT INTO PRODUCTS (NAME, PRICE, STOCK) VALUES
('MAY DO HUYET AP OMRON', 850000.00, 20),
('MAY DO DUONG HUYET', 450000.00, 15);

-- CHÈN VÍ ĐIỆN TỬ
INSERT INTO WALLETS (PATIENT_ID, BALANCE, STATUS) VALUES
(1, 500000.00, 'ACTIVE'),    -- TEST CASE 1: ĐỦ TIỀN THANH TOÁN
(2, 50000.00, 'ACTIVE'),     -- TEST CASE 3: CHÁY VÍ (CHỈ CÓ 50K, KHÔNG ĐỦ KHÁM 200K)
(3, 1000000.00, 'INACTIVE'); -- TEST CASE 2: NHIỀU TIỀN NHƯNG THẺ BỊ KHÓA

DELIMITER //
CREATE PROCEDURE PROCESSEQUIPMENTPURCHASE(
	IN P_PATIENT_ID INT,
    IN P_PRODUCT_ID INT,
    IN P_QUANTITY INT,
    OUT P_MESSAGE VARCHAR(255)
)
BEGIN 
	DECLARE V_PRICE DECIMAL(18,2);
    DECLARE V_STOCK INT;
    DECLARE V_BALANCE DECIMAL(18,2);
    DECLARE V_STATUS VARCHAR(20);
    DECLARE V_TOTAL_COST DECIMAL(18,2);
    
    START TRANSACTION;
    
    -- LẤY THÔNG TIN SẢN PHẨM
    SELECT PRICE, STOCK INTO V_PRICE, V_STOCK FROM PRODUCTS
    WHERE PRODUCT_ID = P_PRODUCT_ID;
    
    -- LẤY THÔNG TIN VÍ
    SELECT BALANCE, STATUS INTO V_BALANCE, V_STATUS FROM WALLETS
    WHERE PATIENT_ID = P_PATIENT_ID;
    
    -- OUT OF STOCK
    IF V_STOCK < P_QUANTITY THEN SET P_MESSAGE = 'THẤT BẠI: KHO KHÔNG ĐỦ SẢN PHẨM';
		ROLLBACK;
    
    -- LOCKED ACCOUNT
    ELSEIF V_STATUS = 'INACTIVE' THEN SET P_MESSAGE = 'THẤT BẠI: VÍ ĐANG BỊ KHÓA';
		ROLLBACK;
        
	ELSE 
		-- TÍNH THÀNH TIỀN = SỐ LƯỢNG * ĐƠN GIÁ
        SET V_TOTAL_COST = P_QUANTITY * V_PRICE;
        
        -- INSUFFICIENT FUNDS
		IF V_BALANCE < V_TOTAL_COST THEN SET P_MESSAGE = 'THẤT BẠI: SỐ DƯ VÍ KHÔNG ĐỦ';
			ROLLBACK;
            
		ELSE
			-- TRỪ SỐ LƯỢNG MUA TƯƠNG ỨNG TRONG BẢNG THIẾT BỊ (PRODUCTS)
            UPDATE PRODUCTS
			SET STOCK = STOCK - P_QUANTITY
            WHERE PRODUCT_ID = P_PRODUCT_ID;
            
            -- TRỪ THÀNH TIỀN VÀO SỐ DƯ VÍ (WALLETS) CỦA BỆNH NHÂN
            UPDATE WALLETS
            SET BALANCE = BALANCE - V_TOTAL_COST
            WHERE PATIENT_ID = P_PATIENT_ID;
            
            -- NẾU KHÔNG CÓ LỖI, LƯU THAY ĐỔI VÀ TRẢ VỀ THÔNG BÁO: "THÀNH CÔNG: ĐÃ XỬ LÝ ĐƠN HÀNG"
            SET P_MESSAGE = 'THÀNH CÔNG: ĐÃ XỬ LÝ ĐƠN HÀNG';
            COMMIT;
		END IF;
	END IF;
END //
DELIMITER ;

SET @TESTING = '';

-- MUA HÀNG HỢP LỆ
CALL PROCESSEQUIPMENTPURCHASE(1, 2, 1, @TESTING);
SELECT @TESTING;

-- LỖI OUT OF STOCK
CALL PROCESSEQUIPMENTPURCHASE(1, 1, 999999, @TESTING);
SELECT @TESTING;

-- LỖI INSUFFICIENT FUNDS
CALL PROCESSEQUIPMENTPURCHASE(2, 2, 1, @TESTING);
SELECT @TESTING;

-- LỖI LOCKED ACCOUNT
CALL PROCESSEQUIPMENTPURCHASE(3, 1, 1, @TESTING);
SELECT @TESTING;
